### PR TITLE
Feature map

### PR DESCRIPTION
**Pull request by ThibaultLahaye**
### Initial Prototype for the Map
An initial version of our chloropleth map build on top of the democracy index dataset.
I think this pull request should go through even though there are some know issues. It is well documented and serves as good startingpoint for integration with the other subgraphs.

image

**Features**
- Zoom and Pan interactivity
- Simple hover functionality

**Known Issues**
- The botton (bottom right) to reset the map back to its initial state after zoming and/or panning. Has a weird issure, where he map does does seem to reset to the default state when the button is clicked, but only after the user attempts to zoom in or out or pan the map. The map should reset to the default state immediately after the button is clicked.
- The title is kinda ugly 
- Alignment of the ticks on the legend of the map

### CODE REVIEW

**Review by BramHamaekers — COMMENTED** [review]
Is it possible to create 5 overarching categories (e.g. very democratic, not democratic, ...). This simplifies the map a bit and allows the use of the same colours used in the UN resolution map?

Additionally, I think it looks nicer if borders with the sea don't have the white line. However, this is only a visual detail and not that important.

When clicking on a nation we can still show the actual democracy index on the right hand side.

**Comment by Arne-L** [comment]
Some additional notes:
* Maybe resize the map such that the title is not on top of the map, but above. Optionally the map can also be made a bit wider, as it currently feels cut-off on the sides.
* More on hover animations, such as highlighting the currently pointed to country (marking the borders and increasing / decreasing the brightness or saturation?)

General note:
If the barcharts allow it, depending on how many categories we eventually decide to go with, we can maybe give the map an increased height

**Comment by ThibaultLahaye** [comment]
I added the UN resolution data, but have yet to inplement the other feedback.

**Comment by Arne-L** [comment]
Would it also be possible to prevent the user from moving the map outside the window? For example that users can move the map around, but that the left map border will always stay on the left? 
Currently it is possible to move the map outside of the window

**Review by Arne-L — APPROVED** [review]

**Pull request merged**
